on:
  push:
    branches: ['*']
  pull_request:
  workflow_dispatch:


jobs:
  check-conventional-commits:
    uses: armakuni/github-actions/.github/workflows/check-conventional-commits.yml@v0.14.10

  lint-pipeline:
    uses: armakuni/github-actions/.github/workflows/lint-pipeline.yml@v0.14.10

  generate-terraform-docs:
    if: github.ref == 'refs/heads/main'
    uses: armakuni/github-actions/.github/workflows/generate-terraform-docs.yml@v0.14.10
    with:
      output-file: README.md
      # This artifact is referenced by the cog.toml
      artifact-name: terraform-docs

  create-release:
    needs:
    - check-conventional-commits
    - lint-pipeline
    if: github.ref == 'refs/heads/main'
    uses: armakuni/github-actions/.github/workflows/tag-and-release.yml@v0.14.10
    permissions:
      contents: write
    with:
      download-artifacts: true

  demo:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: echo "Hello world"

